## Bài làm thêm 3.2 : Phân tích nhiệt độ các ngày trong tuần

Tưởng tượng bạn đang làm việc trong một nhóm các nhà khoa học khí hậu, vai trò của bạn là lấy dữ liệu nhiệt độ các ngày trong  và nhập vào mảng để phân tích sau. Cảm biến ghi lại nhiệt độ 4 lần một ngày từ Thứ Hai đến Thứ Sáu, vào lúc 0:00, 6:00, 12:00 và 18:00. 

Dữ liệu thu được 1 tuần như sau:

Thứ 2: 43.6, 45.1, 58.8, 53,

Thứ 3: 47, 44.5, 58.3, 52.6, 

Thứ 4: 46.7, 44.2, 57.9, 52.2, 

Thứ 5: 46.5, 44.1, 57.6, 51.9, 

Thứ 6: 46.2, 43.9, 57.2, 51.5


**Yêu cầu :**

1. Chuyển dữ liệu đã cho sang 2D numpy array, đặt tên là temperatures 
2. Một trong những nhà nghiên cứu nhận thấy rằng cảm biến đã bị xóa không chính xác và tất cả nhiệt độ được ghi lại là quá lạnh 3.0 độ. Hãy điều chỉnh mảng sao cho số đọc nhiệt độ chính xác (*cộng thêm 3 độ*), và lưu vào biến temperatures_fixed
3. Cho biết các giá trị nhiệt độ ngày thứ Hai, lưu dữ liệu vào biến monday_temperatures.
4. Bạn có thể cho biết dữ liệu lúc 6:00 sáng cho thứ Năm và thứ Sáu không? Lưu dữ liệu này biến thursday_friday_morning.
5. Cho biết tất cả nhiệt độ dưới 50 độ hoặc hơn 60 độ, và lưu vào biến temperature_extremes

In [ ]:
import numpy as np

In [1]:
# Tạo 2D numpy array  temperatures


<details>
  <summary>Nhấn vào đây để xem kết quả !</summary>
  
  <pre>array([[43.6, 45.1, 58.8, 53. ],
       [47. , 44.5, 58.3, 52.6],
       [46.7, 44.2, 57.9, 52.2],
       [46.5, 44.1, 57.6, 51.9],
       [46.2, 43.9, 57.2, 51.5]])</pre>

</details>

In [9]:
# Điều chỉnh lại dữ liệu sao cho số đọc nhiệt độ chính xác
print(temperatures_fixed)

<details>
  <summary>Nhấn vào đây để xem kết quả !</summary>
  
  <pre>[[46.6 48.1 61.8 56. ]
 [50.  47.5 61.3 55.6]
 [49.7 47.2 60.9 55.2]
 [49.5 47.1 60.6 54.9]
 [49.2 46.9 60.2 54.5]]
</pre>

</details>

In [10]:
# Một nhà nghiên cứu khác hỏi bạn về các giá trị nhiệt độ của ngày thứ Hai. 
# Cho biết các giá trị nhiệt độ của ngày thứ Hai


<details>
  <summary>Nhấn vào đây để xem kết quả !</summary>
  
  <pre>[46.6 48.1 61.8 56. ]
</pre>

</details>

In [11]:
# Cho biết các giá trị nhiệt độ lúc 6:00 sáng của ngày thứ Năm và thứ Sáu


<details>
  <summary>Nhấn vào đây để xem kết quả !</summary>
  
  <pre>[47.1 46.9]
</pre>

</details>

In [12]:
# Cho biết tất cả nhiệt độ dưới 50 độ hoặc hơn 60 độ


<details>
  <summary>Nhấn vào đây để xem kết quả !</summary>
  
  <pre>[46.6 48.1 61.8 47.5 61.3 49.7 47.2 60.9 49.5 47.1 60.6 49.2 46.9 60.2]
</pre>

</details>